# Generated by Django 5.1.6 on 2025-05-16 13:59

import django.db.models.deletion
import mainside.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TifUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tif_file', models.FileField(upload_to='tif_regions/', validators=[mainside.models.validate_tif_extension])),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tifs', to='mainside.uploadsession')),
            ],
        ),
        migrations.CreateModel(
            name='KmlUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kml_file', models.FileField(upload_to='raw_kml/', validators=[mainside.models.validate_kml_extension])),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kmls', to='mainside.uploadsession')),
            ],
        ),
    ]
