# Generated by Django 5.1.6 on 2025-05-16 14:16

import mainside.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tifupload',
            name='tif_file',
            field=models.FileField(upload_to='tif_regions_for_scrapper/', validators=[mainside.models.validate_tif_extension]),
        ),
    ]
