# Generated by Django 5.1.6 on 2025-05-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainside', '0003_processedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedFile',
        ),
    ]
