# Generated by Django 5.1.6 on 2025-06-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainside', '0006_processingstatus_can_download_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerrainRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.TextField(unique=True)),
                ('base_tif_path', models.TextField()),
                ('region_path', models.TextField(blank=True, null=True)),
                ('enhanced_path', models.TextField(blank=True, null=True)),
                ('result_path', models.TextField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('session_id', models.CharField(db_index=True, max_length=36)),
            ],
        ),
    ]
