# Generated by Django 5.1.6 on 2025-03-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_path', models.FilePathField()),
                ('time_update', models.DateTimeField()),
                ('interpolation', models.BooleanField()),
                ('watercourses', models.BooleanField()),
                ('relief', models.BooleanField()),
            ],
        ),
    ]
