# Generated by Django 5.1.6 on 2025-03-09 17:38
from django.db import migrations, models

# Тут думаю нужно поменять

class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matrix', models.CharField(max_length=255)),
                ('Date_of_update', models.DateField()),
                ('Processed', models.BooleanField()),
            ],
            options={
                'db_table': 'Region',  # Явно задаем имя таблицы как 'Region'
            },
        ),
    ]